channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.22.0=py35_0
  - backports=1.0=py35_1
  - backports.functools_lru_cache=1.4=py35_1
  - biopython=1.70=py35_2
  - cffi=1.11.2=py35_0
  - chardet=3.0.4=py35_0
  - cryptography=2.1.4=py35_0
  - cycler=0.10.0=py35_0
  - dbus=1.10.22=0
  - decorator=4.1.2=py35_0
  - expat=2.2.5=0
  - fastcluster=1.1.24=py35_0
  - fontconfig=2.12.6=0
  - freetype=2.8.1=0
  - gettext=0.19.7=1
  - glib=2.55.0=0
  - gst-plugins-base=1.8.0=0
  - gstreamer=1.8.0=1
  - h5py=2.7.1=py35_2
  - hdf5=1.10.1=1
  - icu=58.2=0
  - idna=2.6=py35_1
  - ipykernel=4.7.0=py35_0
  - ipython=6.2.1=py35_1
  - ipython_genutils=0.2.0=py35_0
  - jedi=0.10.2=py35_0
  - jpeg=9b=2
  - jupyter_client=5.2.1=py35_0
  - jupyter_core=4.4.0=py_0
  - libffi=3.2.1=3
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libsodium=1.0.15=1
  - libxcb=1.12=1
  - libxml2=2.9.7=0
  - matplotlib=2.1.1=py35_2
  - ncurses=5.9=10
  - openblas=0.2.20=7
  - patsy=0.5.0=py35_0
  - pcre=8.39=0
  - pexpect=4.3.1=py35_0
  - pickleshare=0.7.4=py35_0
  - pip=9.0.1=py35_1
  - prompt_toolkit=1.0.15=py35_0
  - ptyprocess=0.5.2=py35_0
  - pycparser=2.18=py35_0
  - pygments=2.2.0=py35_0
  - pyopenssl=17.4.0=py35_0
  - pyparsing=2.2.0=py35_0
  - pyqt=5.6.0=py35_4
  - pysocks=1.6.8=py35_1
  - python=3.5.4=3
  - python-dateutil=2.6.1=py35_0
  - pytz=2017.3=py_2
  - pyzmq=16.0.2=py35_3
  - qt=5.6.2=7
  - readline=7.0=0
  - requests=2.18.4=py35_1
  - scikit-garden=0.1.3=py35_0
  - scikit-optimize=0.4=py_0
  - seaborn=0.8.1=py35_0
  - setuptools=38.4.0=py35_0
  - simplegeneric=0.8.1=py35_0
  - sip=4.18=py35_1
  - six=1.11.0=py35_1
  - sqlite=3.20.1=2
  - statsmodels=0.8.0=py35_0
  - tk=8.6.7=0
  - tornado=4.5.3=py35_0
  - traitlets=4.3.2=py35_0
  - urllib3=1.22=py35_0
  - wcwidth=0.1.7=py35_0
  - wheel=0.30.0=py35_2
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - xz=5.2.3=0
  - zeromq=4.2.1=1
  - zlib=1.2.11=0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py35_1
  - intel-openmp=2019.1=144
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py35h7dd41cf_0
  - mkl_random=1.0.1=py35h4414c95_1
  - numpy=1.15.2=py35h1d66e8a_0
  - numpy-base=1.15.2=py35h81de0dd_0
  - openssl=1.0.2p=h14c3975_0
  - pandas=0.23.4=py35h04863e7_0
  - scikit-learn=0.20.0=py35h4989274_1
  - scipy=1.1.0=py35hfa4b5c9_1
  - pip:
    - commonmark==0.5.4
    - humanize==0.5.1
    - ipdbplugin==1.5.0
    - jug==1.6.5
    - nbsphinx==0.3.1
    - nose==1.3.7
    - numpydoc==0.7.0
    - pymc3==3.0rc1
    - recommonmark==0.4.0
    - redis==2.10.6
    - theano==1.0.1
